DROP DATABASE IF EXISTS role_db;

CREATE DATABASE role_db;

USE role_db;

CREATE TABLE role (
	id INTEGER NOT NULL AUTO_INCREMENT,
    title VARCHAR(30) NOT NULL,
	salary DECIMAL NOT NULL,
	department_id INT NOT NULL,
    PRIMARY KEY(id)
);

SELECT * FROM role;